// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_tf_jira

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func TfJiraProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type TfJiraModel struct {
}
